import './globals.css'
import { Inter } from 'next/font/google'

import { Navegation } from './components/Navegation'
const inter = Inter({ subsets: ['latin'] })


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>My first app con el midu</title>
      </head>
      <body className={inter.className}>
        <Navegation />

        {children}
      </body>
    </html>
  )
}
